# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PhotoCollection_practice' do
   pod 'Alamofire', '~> 5.2'
   pod 'SnapKit', '~> 4.0.0'
   pod 'SwiftyJSON', '~> 4.0'
   pod 'SDWebImage', '~> 4.0'
   pod 'KeychainSwift', '~> 19.0'
   pod 'PanModal'
   pod 'SkyFloatingLabelTextField', '~> 3.0'

   pod "PagingKit" # add

end
