# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'parallaxPlz_practice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for parallaxPlz_practice
  pod "MXParallaxHeader"

  target 'parallaxPlz_practiceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'parallaxPlz_practiceUITests' do
    # Pods for testing
  end

end
