# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'materialCard_Practice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for materialCard_Practice
  pod "MaterialComponents/Cards"
  pod 'MaterialComponents/Cards+ShapeThemer'

  target 'materialCard_PracticeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'materialCard_PracticeUITests' do
    # Pods for testing
  end

end
