# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'foldincTableChangeFooter_practice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'ExpyTableView'
  pod 'MaterialComponents'

  # Pods for foldincTableChangeFooter_practice

  target 'foldincTableChangeFooter_practiceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'foldincTableChangeFooter_practiceUITests' do
    # Pods for testing
  end

end
