# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TodoList_practice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TodoList_practice
  pod 'RealmSwift'
  target 'TodoList_practiceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TodoList_practiceUITests' do
    # Pods for testing
  end

end
