# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ParallaxWithPager_practice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ParallaxWithPager_practice
  pod "PagingKit" # add
  pod "MXParallaxHeader"
  pod 'PageMenu' 
  target 'ParallaxWithPager_practiceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ParallaxWithPager_practiceUITests' do
    # Pods for testing
  end

end
