# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'drawing_practice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  

  # Pods for drawing_practice
  pod 'SnapKit', '~> 5.0.0'
  target 'drawing_practiceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'drawing_practiceUITests' do
    # Pods for testing
  end

end
